version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - doto
  - drei
  - eslintcache
  - fontless
  - fontsource
  - importantimport
  - masknet
  - moeru
  - ROND
ignoreWords: []
import: []
